services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./logs:/var/logs
    networks:
      - laravel-net

  web:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "8080:80"  # 外部アクセス用のポート設定 (例: http://localhost:8080)
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net

  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel-net

volumes:
  db_data:

networks:
  laravel-net:
